theme = "github_dark"

[editor]
bufferline = "multiple"
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
