theme = "github_dark"

[editor]
bufferline = "multiple"
mouse = false
line-number = "relative"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[editor.cursor-shape]
insert = "bar"
